# API.
http_addr: ":6029"

# Metrics & pprof.
debug_http_addr: ":6060"

# Max request processing time.
# Default: 2m.
http_handler_timeout: 2m

# Max output file weight (file size heuristic).
# Default: 52428800 (50 Mb)
max_excel_file_size_bytes: 104857600 # (100 MB)

# Name of the request cookie that service forwards to YT.
# YT proxy uses this cookie to authorize requester.
# Default: Session_id.
# Reasonable value for OS installation: YTCypressCookie
auth_cookie_name: ""

# Name of the cookie that contains SSO token. This cookie
# is used similarly to auth_cookie_name, but it is only
# valid when the user is logged in using SSO instead of
# their credentials.
# Default: yt_oauth_access_token
sso_cookie_name: ""


# CORS settings.
cors:
  # Allowed hostnames e.g. myorigin.com, checked via exact match: origin.Host == "myorigin.com"
  allowed_hosts: []
  # Allowed hostname suffixes e.g. .myorigin.com, checked via HasSuffix(origin.Host, ".myorigin.com")
  allowed_host_suffixes: []

# List of clusters with cluster-specific settings.
clusters:
  - proxy: hahn
    # Specifies proxy alias used in API endpoint path:
    #   <http_addr>/<api_endpoint_name>/api/
    # Default: equals to proxy.
    api_endpoint_name: hahn
